services:
  manager:
    build: .
    container_name: apps-manager
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Hier passiert die Magie
      - /opt/apps/services:/opt/apps/services     # Zugriff auf die Apps
      - /opt/apps/manager/apps.json:/opt/apps/manager/apps.json
    ports:
      - "8000:8000"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
